qr_pass/pass/urls.py
from django.urls import path

from . import views


app_name = 'passes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('edit/<str:nick>', views.edit, name='edit'),
    path('delete/<str:nick>', views.delete, name='delete'),
    path('get-qr/<str:key>', views.get_qr, name='get_qr'),
    path('check/<str:key>', views.check, name='check'),
    path('logs/', views.logs, name='logs'),
]

qr_pass/qr_pass/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pass.urls', namespace='passes')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

qr_pass/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='login.html'),
        name='login'
    ),
]

qr_pass/pass/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Customer(models.Model):
    username = models.CharField(
        max_length=100,
        verbose_name='Ник посетителя',
        unique=True
    )
    real_name = models.CharField(
        max_length=200,
        verbose_name='Реальное имя посетителя',
        blank=True
    )
    access = models.BooleanField(
        default=False,
        verbose_name='Доступ'
    )
    key = models.CharField(
        max_length=20,
        verbose_name='секретный ключ',
        default='11111111111111111111'
    )
    master = models.ForeignKey(
        User,
        verbose_name="Создатель",
        on_delete=models.CASCADE,
        related_name='customers'
    )

    def __str__(self):
        return self.username


class Logs(models.Model):
    user = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        verbose_name='Ник посетителя',
        related_name='logos'

    )
    visit = models.DateTimeField(
        verbose_name='Время входа',
        auto_now_add=True
    )
    success = models.BooleanField(
        verbose_name='Попытка входа',
        default=False
    )

    class Meta:
        ordering = ('-visit',)

qr_pass/pass/forms.py
from django import forms

from .models import Customer


class PassForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = (
            'username', 'real_name', 'access'
        )

qr_pass/pass/views.py
import datetime as dt

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Customer, Logs
from .forms import PassForm
from .telegram import send_message


def create_key():
    return (str(dt.datetime.now())
            .replace(' ', '')
            .replace('-', '')
            .replace(':', '')
            .replace('.', '')
            )


@login_required
def index(request):
    template = 'index.html'
    var = Customer.objects.filter(master=request.user)
    form = PassForm()
    context = {
        'var': var,
        'form': form
    }
    return render(request, template, context)


@login_required
def create(request):
    form = PassForm(request.POST or None)
    if form.is_valid():
        new_rec = form.save(commit=False)
        new_rec.key = create_key()
        new_rec.master = request.user
        new_rec.save()
    return redirect('passes:index')


@login_required
def edit(request, nick):
    user = get_object_or_404(Customer, username=nick)
    if user.master == request.user:
        form = PassForm(
            request.POST or None,
            instance=user
        )
        if form.is_valid():
            form.save()
            return redirect('passes:index')
        template = 'index.html'
        var = Customer.objects.filter(master=request.user)
        context = {
            'var': var,
            'form': form,
            'is_edit': True,
            'nick': nick
        }
        return render(request, template, context)
    else:
        return redirect('passes:index')


@login_required
def delete(request, nick):
    user = get_object_or_404(Customer, username=nick)
    if user.master == request.user:
        user.delete()
    return redirect('passes:index')


@login_required
def get_qr(request, key):
    api_url = 'https://qrcode.tec-it.com/API/QRCode?data='
    my_url = 'http://unplugged.pythonanywhere.com/check/'
    url = api_url + my_url + key
    template = 'qr.html'
    context = {
        'url': url
    }
    return render(request, template, context)


def check(request, key):
    template = 'access.html'
    try:
        user = get_object_or_404(Customer, key=key)
    except Exception:
        send_message(
            f'Попытка использовать неверный код:  {key}'
            f'\nДата попытки: {str(dt.datetime.now())[:-7]}'
        )
        return render(request, 'bad_qr.html')
    Logs.objects.create(user=user, success=user.access)
    message = (
            'Доступ запросил: ' +
            str(user.real_name) +
            ' (' + str(user) + ')' +
            '\nПолучил доступ: ' + str(user.access) +
            '\nДоступ получен в: ' + str(dt.datetime.now())[:-7]
    )
    send_message(message)
    context = {
        'access': user.access,
        'name': user.real_name
    }
    return render(request, template, context)


@login_required
def logs(request):
    template = 'logs.html'
    log = Logs.objects.filter(user__master=request.user)
    context = {
        'log': log,
    }
    return render(request, template, context)

qr_pass/templates/access.html
{% extends 'base.html' %}

{% block title %}Доступ{% endblock %}
{% block content %}
{% if access %}
<div class="col d-flex justify-content-center">
  <div class="card text-white text-center bg-success mb-3" style="max-width: 36rem;">
    <div class="card-header">{{ name }}</div>
      <div class="card-body">
        <h1 class="card-title">ДОСТУП РАЗРЕШЕН</h1>
      </div>
  </div>
</div>
{% else %}
<div class="col d-flex justify-content-center">
  <div class="card text-white text-center bg-danger mb-3" style="max-width: 36rem;">
    <div class="card-header">{{ name }}</div>
      <div class="card-body">
        <h1 class="card-title">ДОСТУП ЗАПРЕЩЕН</h1>
      </div>
  </div>
</div>
{% endif %}
{% endblock %}

qr_pass/templates/bad_qr.html
{% extends 'base.html' %}

{% block title %}Неверный QR код{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card text-white text-center bg-danger mb-3" style="max-width: 36rem;">
    <div class="card-header">Неверный QR код!</div>
      <div class="card-body">
        <h1 class="card-title">ДОСТУП ЗАПРЕЩЕН</h1>
      </div>
  </div>
</div>
{% endblock %}

qr_pass/templates/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>

    <body>
        <header>
            {% include 'includes/header.html' %}
        </header>
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer class="border-top text-center py-3">
            {% include 'includes/footer.html' %}
        </footer>
    </body>
</html>

qr_pass/templates/includes/footer.html
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
  <div class="container-fluid">
    <p>QR Pass @ {% now "Y" %} by Nikolai Popov</p>
  </div>
</nav>

qr_pass/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">QR Pass</a>
      {% if user.is_authenticated %}
    <div class="nav-item" style="color:blue;">Пользователь: {{ user.username }}</div>
      {% endif %}
  </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'passes:index' %}">Управление</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'passes:logs' %}">Логи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
      {% else %}
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
      {% endif %}
        </li>
      </ul>
    </div>
</nav>

qr_pass/templates/index.html
{% extends 'base.html' %}

{% block title %}Панель управления{% endblock %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Ник</th>
      <th scope="col">Полное имя</th>
      <th scope="col">Доступ</th>
      <th scope="col">Получить QR</th>
      <th scope="col">Редактировать</th>
      <th scope="col">Удалить</th>
    </tr>
  </thead>
  <tbody>
  {% for v in var %}
    <tr>
      <td>{{ v.username }}</td>
      <td>{{ v.real_name }}</td>
      <td>
          {% if v.access == True %}
            <span style="color:green;">ДОСТУП РАЗРЕШЕН</span>
          {% else %}
            <span style="color:red;">ДОСТУП ЗАПРЕЩЕН</span>
          {% endif %}
      </td>
      <td>
          <a href="{% url 'passes:get_qr' v.key %}" type="button" class="btn btn-info">QR</a>
      </td>
      <td>
          <a href="{% url 'passes:edit' v.username %}" type="button" class="btn btn-primary">Редактировать</a>
      </td>
      <td>
          <a href="{% url 'passes:delete' v.username %}"  type="button" class="btn btn-danger">Удалить</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<div class="container">
  <form method="post" action="
      {% if is_edit %}
        {% url 'passes:edit' nick %}
      {% else %}
        {% url 'passes:create' %}
      {% endif %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success">
      {% if is_edit %}
        Сохранить
      {% else %}
        Создать
      {% endif %}
    </button>
  </form>
</div>
{% endblock %}

qr_pass/templates/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

qr_pass/templates/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >

            {% csrf_token %}
            <div class="form-group row my-3">
              <label for="id_username">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>
              <input type="text" name="username" autofocus class="form-control" required id="id_username">
            </div>
            <div class="form-group row my-3">
              <label for="id_password">
                Пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="password" class="form-control" required id="id_password">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

qr_pass/templates/logs.html
{% extends 'base.html' %}

{% block title %}Логи{% endblock %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Ник</th>
      <th scope="col">Реальное имя</th>
      <th scope="col">Время входа</th>
      <th scope="col">Доступ</th>
    </tr>
  </thead>
  <tbody>
  {% for l in log %}
    <tr>
      <td>{{ l.user }}</td>
      <td>{{ l.user.real_name }}</td>
      <td>{{ l.visit }}</td>
      <td>{{ l.success }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

qr_pass/templates/qr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QR</title>
</head>
<body>
<img src="{{ url }}" />
</body>
</html>